[colors.primary]
background = '#0e150a'
foreground = '#dde5d1'

[colors.cursor]
text = '#0e150a'
cursor = '#dde5d1'

[colors.vi_mode_cursor]
text = '#0e150a'
cursor = '#b6ff89'

[colors.search.matches]
foreground = '#3f4a36'
background = '#a5ffc3'

[colors.search.focused_match]
foreground = '#3f4a36'
background = '#b6ff89'

[colors.footer_bar]
foreground = '#3f4a36'
background = '#dde5d1'

[colors.hints.start]
foreground = '#3f4a36'
background = '#93d968'

[colors.hints.end]
foreground = '#3f4a36'
background = '#93d968'

[colors.selection]
text = '#becbb0'
background = '#3f4a36'


[colors.normal]
black   = '#3f4a36'
red     = '#ffb4ab'
green   = '#b6ff89'
yellow  = '#93d968'
blue    = '#a5ffc3'
magenta = '#68e110'
cyan    = '#93d968'
white   = '#dde5d1'


[colors.bright]
black   = '#88957c'
red     = '#ffb4ab'
green   = '#b6ff89'
yellow  = '#93d968'
blue    = '#a5ffc3'
magenta = '#68e110'
cyan    = '#93d968'
white   = '#dde5d1'


[colors.dim]
black   = '#3f4a36'
red     = '#ffb4ab'
green   = '#b6ff89'
yellow  = '#93d968'
blue    = '#a5ffc3'
magenta = '#68e110'
cyan    = '#93d968'
white   = '#dde5d1'
