[colors.primary]
background = '#1f2430'
foreground = '#d1d1c7'

[colors.cursor]
text = '#1f2430'
cursor = '#ffcc66'

[colors.vi_mode_cursor]
text = '#0b0e14'
cursor = '#e6b450'

[colors.search.matches]
foreground = '#1e222a'
background = '#39bae6'

[colors.search.focused_match]
foreground = '#1e222a'
background = '#e6b450'

[colors.footer_bar]
foreground = '#1e222a'
background = '#e3e5e8'

[colors.hints.start]
foreground = '#1e222a'
background = '#aad94c'

[colors.hints.end]
foreground = '#1e222a'
background = '#aad94c'

[colors.selection]
text = '#1f2430'
background = '#409fff'


[colors.normal]
black   = '#171b24'
red     = '#ed8274'
green   = '#87d96c'
yellow  = '#facc6e'
blue    = '#6dcbfa'
magenta = '#dabafa'
cyan    = '#90e1c6'
white   = '#c7c7c7'


[colors.bright]
black   = '#686868'
red     = '#f28779'
green   = '#d5ff80'
yellow  = '#ffd173'
blue    = '#73d0ff'
magenta = '#dfbfff'
cyan    = '#95e6cb'
white   = '#ffffff'


[colors.dim]
black   = '#171b24'
red     = '#ed8274'
green   = '#87d96c'
yellow  = '#facc6e'
blue    = '#6dcbfa'
magenta = '#dabafa'
cyan    = '#90e1c6'
white   = '#c7c7c7'
