color0 #3f4a36
color1 #ffb4ab
color2 #b6ff89
color3 #93d968
color4 #a5ffc3
color5 #68e110
color6 #93d968
color7 #dde5d1
color8 #88957c
color9 #ffb4ab
color10 #b6ff89
color11 #93d968
color12 #a5ffc3
color13 #68e110
color14 #93d968
color15 #dde5d1

cursor                #dde5d1
cursor_text_color     #0e150a
background            #0e150a
foreground            #dde5d1
selection_foreground  #becbb0
selection_background  #3f4a36
active_border_color   #b6ff89
inactive_border_color #3f4a36
url_color             #b6ff89

active_tab_foreground   #143800
active_tab_background   #b6ff89
inactive_tab_foreground #becbb0
inactive_tab_background #3f4a36
cursor_trail_color      #becbb0
