

# Font
font_family CaskaydiaMono Nerd Font
bold_italic_font auto
font_size        16

# Window
window_padding_width 0
window_padding_height 0
# hide_window_decorations yes
show_window_resize_notification no
confirm_os_window_close 0

# Keybindings
map ctrl+insert copy_to_clipboard
map shift+insert paste_from_clipboard

# Allow remote access
single_instance yes
allow_remote_control yes

# Aesthetics
cursor_shape block
enable_audio_bell no

# Minimal Tab bar styling
tab_bar_edge                bottom
tab_bar_style               powerline
tab_powerline_style         slanted
tab_title_template          {title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}

copy_on_select yes

# layout
enabled_layouts splits:split_axis=horizontal

# Splits
map ctrl+shift+e launch --location=hsplit
map ctrl+shift+o launch --location=vsplit

# Redimensionar splits usando Ctrl + Shift + Setas (Geralmente livre no GNOME)
map ctrl+shift+right  resize_window narrower 2
map ctrl+shift+left resize_window wider 2
map ctrl+shift+up    resize_window taller 2
map ctrl+shift+down  resize_window shorter 2

# OU usando Alt + R e depois as letras (Modo de redimensionamento)
map alt+r start_resizing_window


# Navegação rápida entre splits (estilo Vim)
map ctrl+left  neighboring_window left
map ctrl+right neighboring_window right
map ctrl+up    neighboring_window up
map ctrl+down  neighboring_window down




